-- Add comprehensive personal and business fields to profiles table
ALTER TABLE public.profiles 
ADD COLUMN first_name TEXT,
ADD COLUMN last_name TEXT,
ADD COLUMN phone TEXT,
ADD COLUMN date_of_birth DATE,
ADD COLUMN gender TEXT,
ADD COLUMN address_line1 TEXT,
ADD COLUMN address_line2 TEXT,
ADD COLUMN city TEXT,
ADD COLUMN state TEXT,
ADD COLUMN postal_code TEXT,
ADD COLUMN country TEXT,
ADD COLUMN company_name TEXT,
ADD COLUMN job_title TEXT,
ADD COLUMN department TEXT,
ADD COLUMN business_phone TEXT,
ADD COLUMN business_email TEXT,
ADD COLUMN business_address_line1 TEXT,
ADD COLUMN business_address_line2 TEXT,
ADD COLUMN business_city TEXT,
ADD COLUMN business_state TEXT,
ADD COLUMN business_postal_code TEXT,
ADD COLUMN business_country TEXT,
ADD COLUMN website TEXT,
ADD COLUMN linkedin_url TEXT,
ADD COLUMN bio TEXT;